---
- name: setting DROP
  shell: {{ item }}
  tags: firewalld
  with_items: "{{ firewalld_drops }}"
  
- name: setting INPUT
  shell: {{ item }}
  tags: firewalld
  with_items: "{{ firewalld_inputs }}"

- name: setting PORT
  shell: firewall-cmd --add-port={{ ssh_port }}/tcp --permanent
  tags: firewalld

- name: set rule to public
  shell: firewall-cmd --permanent --zone=public --set-target=DROP
  tags: firewalld

- name: reload firewalld
  shell: firewall-cmd --reload
  tags: firewalld
    